language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

 
script:
  - npm start

after_script:
  - cd ./public
  - git init
  - git config user.name "fyc1007261"
  - git config user.email "fyc1007261@live.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GithubToken}@${GH_REF}" master:master


